kermit-webui/kermit_new-webui/webui/platforms/bar/urls.py
'''
Created on Aug 18, 2011

@author: mmornati
'''

from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('webui.platforms.bar.views',
  url(r'^details/(?P<hostname>[\w|\W]+)/(?P<console_name>[\w|\W]+)/(?P<resource_name>[\w|\W]+)/pools/$', 'poolsInventory', name = "bar_pools_details"),
  url(r'^details/(?P<hostname>[\w|\W]+)/(?P<console_name>[\w|\W]+)/(?P<resource_name>[\w|\W]+)/pool/$', 'poolInventory', name = "bar_pool_details"),
  url(r'^details/(?P<hostname>[\w|\W]+)/(?P<console_name>[\w|\W]+)/(?P<resource_name>[\w|\W]+)/bar/$', 'barInventory', name = "bar_details"),
  url(r'^details/(?P<hostname>[\w|\W]+)/(?P<console_name>[\w|\W]+)/(?P<resource_name>[\w|\W]+)/console/$', 'barConsoleInventory', name = "bar_console_details"),
  
  url(r'^get_deploy_form/(?P<dialog_name>[\w|\W]+)/(?P<action>[\w|\W]+)/(?P<filters>[\w|\W]+)/$', 'get_deploy_form', name = "bar_get_deploy_form"),
  url(r'^barlist/(?P<filters>[\w|\W]+)/$', 'get_bar_list', name = "bar_list"),
  url(r'^deploy/(?P<filters>[\w|\W]+)/(?P<dialog_name>[\w|\W]+)/(?P<xhr>.*)', 'deploy_bar', name = "bar_deploy"),
)

kermit-webui/kermit_new-webui/webui/platforms/oc4j/urls.py
'''
Created on Aug 18, 2011

@author: mmornati
'''

from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('webui.platforms.oc4j.views',
  url(r'^details/(?P<hostname>[\w|\W]+)/(?P<instance_name>[\w|\W]+)/(?P<resource_name>[\w|\W]+)/instance/$', 'instanceInventory', name = "oc4j_instance_details"),
  url(r'^details/(?P<hostname>[\w|\W]+)/(?P<instance_name>[\w|\W]+)/(?P<resource_name>[\w|\W]+)/datasources/$', 'datasourceListInventory', name = "oc4j_datasources_details"),
  url(r'^details/(?P<hostname>[\w|\W]+)/(?P<instance_name>[\w|\W]+)/(?P<resource_name>[\w|\W]+)/datasource/$', 'datasourceInventory', name = "oc4j_datasource_details"),
  url(r'^details/(?P<hostname>[\w|\W]+)/(?P<instance_name>[\w|\W]+)/(?P<resource_name>[\w|\W]+)/application/$', 'applicationInventory', name = "oc4j_application_details"),
  
  url(r'^applist/(?P<filters>[\w|\W]+)/(?P<type>[\w|\W]+)/$', 'get_app_list', name = "oc4j_app_list"),
  url(r'^instancelist/(?P<filters>[\w|\W]+)/$', 'get_instance_list', name = "oc4j_instance_list"),
  url(r'^deploy/(?P<filters>[\w|\W]+)/(?P<dialog_name>[\w|\W]+)/(?P<xhr>.*)', 'deploy_app', name = "oc4j_deploy_app"),
  url(r'^get_deploy_form/(?P<dialog_name>[\w|\W]+)/(?P<action>[\w|\W]+)/(?P<filters>[\w|\W]+)/$', 'get_deploy_form', name = "oc4j_get_deploy_form"),
  
  url(r'^get_form/(?P<dialog_name>[\w|\W]+)/(?P<action>[\w|\W]+)/(?P<filters>[\w|\W]+)/$', 'get_form', name = "oc4j_get_form"),
  url(r'^create_instance/(?P<filters>[\w|\W]+)/(?P<dialog_name>[\w|\W]+)/(?P<xhr>.*)', 'create_instance', name = "oc4j_create_instance"),
  url(r'^add_pool/(?P<filters>[\w|\W]+)/(?P<dialog_name>[\w|\W]+)/(?P<xhr>.*)', 'add_pool', name = "oc4j_add_pool"),
  
  url(r'^get_log_form/(?P<dialog_name>[\w|\W]+)/(?P<action>[\w|\W]+)/(?P<filters>[\w|\W]+)/$', 'get_log_form', name = "oc4j_get_log_form"),
  url(r'^log/(?P<filters>[\w|\W]+)/(?P<dialog_name>[\w|\W]+)/(?P<xhr>.*)', 'get_log', name = "oc4j_get_log"),
  url(r'^get_log_file/(?P<file_name>[\w|\W]+)/$', 'get_log_file', name = "oc4j_get_log_file"),
  
)

kermit-webui/kermit_new-webui/webui/platforms/urls.py
from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('',
    (r'^oc4j/', include('webui.platforms.oc4j.urls')),
    (r'^weblogic/', include('webui.platforms.weblogic.urls')),
    (r'^bar/', include('webui.platforms.bar.urls')),
    (r'^jboss/', include('webui.platforms.jboss.urls')),
    (r'^postgresql/', include('webui.platforms.postgresql.urls')),
    (r'^oracledb/', include('webui.platforms.oracledb.urls')),
    (r'^virtualization/', include('webui.platforms.virtualization.urls')),
    
    url(r'^application/(?P<appname>[\w|\W]+)/$', 'webui.platforms.views.appdetails', name = "application_details"),
)

kermit-webui/kermit_new-webui/webui/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from webui import initialize
initialize()

#Look for cron jobs
if 'webui.django_cron' in settings.INSTALLED_APPS:
    import django_cron
    django_cron.autodiscover()

#Discovering all widgets
if 'webui.widgets' in settings.INSTALLED_APPS:
    from widgets.loading import registry
    registry.discover_widgets()
    
#import platforms
#platforms.initialize()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'webui.views.home', name='home'),
    # url(r'^webui/', include('webui.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    (r'^grappelli/', include('grappelli.urls')),
    (r'^server/', include('webui.serverdetails.urls')),
    (r'^restapi/', include('webui.restserver.urls')),
    (r'^puppetclasses/', include('webui.puppetclasses.urls')),
    (r'^agent/', include('webui.agent.urls')),
    (r'^index/(.*)', include('webui.index.urls')),
    (r'^platform/', include('webui.platforms.urls')),
    (r'^accounts/login/$', 'django.contrib.auth.views.login'),
    (r'^accounts/logout/$', 'webui.index.views.logout_view'),
    (r'^export/', include('webui.exporter.urls')),
    (r'^auth/', include('webui.authentication.urls')),
    (r'^upload/', include('webui.upload.urls')),
    (r'^progress/', include('webui.progress.urls')),
    (r'^alerts/', include('webui.alerting.urls')),
    (r'^chain/', include('webui.chain.urls')),
    
    #(r'^wsgroups/', include('a7x_wsgroups.urls')),
    
    (r'', include('webui.index.urls')),
)

kermit-webui/kermit_new-webui/webui/platforms/bar/forms.py
'''
Created on Sep 9, 2011

@author: mmornati
'''
from django import forms

class DeployForm(forms.Form):
    bcname = forms.CharField(label=u"BarConsole Name", required=True)
    barname = forms.ChoiceField(label=u"Bar name", required=True)

kermit-webui/kermit_new-webui/webui/platforms/jboss/forms.py
'''
Created on Sep 9, 2011

@author: mmornati
'''
from django import forms
from webui.platforms.jboss import settings


class DeployForm(forms.Form):
    types = forms.ChoiceField(choices=settings.AVAILABLE_TYPES, required=True)
    applist = forms.ChoiceField(label=u"Available application", required=True)
    instancename = forms.ChoiceField(label=u"Instance Name", required=True)
    
class LogForm(forms.Form):
    instancename = forms.ChoiceField(label=u"Instance Name", required=True)

kermit-webui/kermit_new-webui/webui/platforms/oc4j/forms.py
'''
Created on Sep 9, 2011

@author: mmornati
'''
from django import forms
from webui.platforms.oc4j import settings

class DeployForm(forms.Form):
    types = forms.ChoiceField(choices=settings.AVAILABLE_TYPES, required=True)
    applist = forms.ChoiceField(label=u"Available application", required=True)
    instancename = forms.ChoiceField(label=u"Instance Name", required=True)
    appname = forms.CharField(label=u"Application Name", required=True)
    
class LogForm(forms.Form):
    instancename = forms.ChoiceField(label=u"Instance Name", required=True)
    appname = forms.CharField(label=u"Application Name", required=True)
    
class InstanceForm(forms.Form):
    instancename = forms.CharField(label=u"Instance Name", required=True)
    groupname = forms.CharField(label=u"Group Name", required=True)
    isflow = forms.CharField(label=u"Is Flow?", required=False)
    
class PoolForm(forms.Form):
    poolname = forms.CharField(label=u"Pool name", required=True)
    instancename = forms.CharField(label=u"Oc4J Name", required=True)
    username = forms.CharField(label=u"Database Username", required=True)
    password = forms.CharField(widget=forms.PasswordInput, label=u"Database Password", required=True)
    database = forms.CharField(label=u"Server Name", required=True)
    dbinstance = forms.CharField(label=u"Database Instance", required=True)
    

kermit-webui/kermit_new-webui/webui/platforms/postgresql/forms.py
'''
Created on Sep 9, 2011

@author: mmornati
'''
from django import forms

class SqlExecuteForm(forms.Form):
    sqllist = forms.ChoiceField(label=u"Available sqls", required=True)
    dbname = forms.CharField(label=u"Database Name", required=True)

kermit-webui/kermit_new-webui/webui/platforms/bar/views.py
# Create your views here.
from webui.platforms.bar.communication import read_server_info
from django.contrib.auth.decorators import login_required
from webui.platforms.utils import convert_keys_names
from django.shortcuts import render_to_response
from webui import settings
from django.template.context import RequestContext
import logging
from guardian.decorators import permission_required
from webui.platforms.bar.forms import DeployForm
from django.http import HttpResponse, HttpResponseRedirect, Http404
from webui.platforms.bar.utils import get_available_bars
from webui.restserver.communication import callRestServer
from django.utils import simplejson as json

logger = logging.getLogger(__name__)

@login_required()
def poolInventory(request, hostname, console_name, resource_name):
    server_info = read_server_info(hostname)
    if server_info:
        selected_console = None 
        for console in server_info:
            if console['consolename'] == console_name:
                selected_console = console
                break 
        resource_name = resource_name.replace('_', '/')
        pool = None
        for current in selected_console['poollist']:
            if current['poolname'] == resource_name:
                pool = current
                convert_keys_names(pool)
                break
        return render_to_response('platforms/bar/datasource.html', {"base_url": settings.BASE_URL, "static_url":settings.STATIC_URL, "datasource": pool}, context_instance=RequestContext(request))
    else:
        return render_to_response('platforms/bar/datasource.html', {"base_url": settings.BASE_URL, "static_url":settings.STATIC_URL, "hostname": hostname}, context_instance=RequestContext(request))

@login_required()
def poolsInventory(request, hostname, console_name, resource_name):
    server_info = read_server_info(hostname)
    if server_info:
        selected_console = None 
        for console in server_info:
            if console['consolename'] == console_name:
                selected_console = console
                break 
        resource_name = resource_name.replace('_', '/')
        return render_to_response('platforms/bar/datasources.html', {"base_url": settings.BASE_URL, "static_url":settings.STATIC_URL, "datasources": selected_console['poollist']}, context_instance=RequestContext(request))
    else:
        return render_to_response('platforms/bar/datasources.html', {"base_url": settings.BASE_URL, "static_url":settings.STATIC_URL, "hostname": hostname}, context_instance=RequestContext(request))


@login_required()
def barInventory(request, hostname, console_name, resource_name):
    server_info = read_server_info(hostname)
    if server_info:
        selected_console = None 
        for console in server_info:
            if console['consolename'] == console_name:
                selected_console = console
                break 
        selected_bar = None 
        for bar in selected_console['barlist']:
            if bar['name'] == resource_name:
                selected_bar = bar
                break
        #Retrieving datasource information
        if "resources" in selected_bar:
            pool_info = []
            for pool in selected_bar['resources']:
                for retrieved_ds in selected_console['poollist']:
                    if retrieved_ds['poolname'] == pool:
                        convert_keys_names(retrieved_ds)  
                        pool_info.append(retrieved_ds)
                        break
            selected_bar['datasources'] = pool_info    
        else:
            logger.debug("No poollist key found for %s" % console['consolename'])
            
        convert_keys_names(selected_bar)        
        return render_to_response('platforms/bar/batch.html', {"base_url": settings.BASE_URL, "static_url":settings.STATIC_URL,"hostname":hostname, "bar":selected_bar}, context_instance=RequestContext(request))
    else:
        return render_to_response('platforms/bar/batch.html', {"base_url": settings.BASE_URL, "static_url":settings.STATIC_URL, "hostname": hostname}, context_instance=RequestContext(request))


@login_required()
def barConsoleInventory(request, hostname, console_name, resource_name):
    server_info = read_server_info(hostname)
    if server_info:
        selected_console = None 
        for console in server_info:
            if console['consolename'] == console_name:
                selected_console = console
                break 
        
        if 'java_ver' in selected_console:
            java_version = selected_console["java_ver"]
        else:
            java_version = ""
              
        return render_to_response('platforms/bar/console.html', {"base_url": settings.BASE_URL, "static_url":settings.STATIC_URL,"hostname":hostname, "java_version":java_version}, context_instance=RequestContext(request))
    else:
        return render_to_response('platforms/bar/console.html', {"base_url": settings.BASE_URL, "static_url":settings.STATIC_URL, "hostname": hostname}, context_instance=RequestContext(request))


@login_required()
@permission_required('agent.call_mcollective', return_403=True)
def get_deploy_form(request, dialog_name, action, filters):
    logger.debug('Rendering form')         
    return render_to_response('platforms/bar/deployform.html', {'action':action, 'filters':filters, 'form':DeployForm([]), 'dialog_name': dialog_name, 'base_url':settings.BASE_URL}, context_instance=RequestContext(request))

@login_required()
@permission_required('agent.call_mcollective', return_403=True)
def get_bar_list(request, filters):
    return HttpResponse(get_available_bars(request.user, filters))

@login_required()
@permission_required('agent.call_mcollective', return_403=True)
def deploy_bar(request, filters, dialog_name, xhr=None):
    if request.method == "POST":
        logger.debug("Recreating form")
        form = DeployForm(request.POST)

        #Check if the <xhr> var had something passed to it.
        if xhr == "xhr":
            #TODO: Try to use dynamic form validation
            clean = form.is_valid()
            rdict = {'bad':'false', 'filters':filters }
            try:
                bcname = request.POST['bcname']
                barname = request.POST['barname']
            except:
                bcname=None
                barname=None
            if bcname and barname:
                logger.debug("Parameters check: OK.")
                logger.debug("Calling MCollective to deploy %s application on %s filtered server" % (barname, filters))
                response, content = callRestServer(request.user, filters, 'a7xbar', 'deploy', 'bcname=%s;filename=%s' %(bcname, barname), True)
                if response.status == 200:
                    json_content = json.loads(content)
                    s_resps = []
                    for server_response in json_content:
                        if server_response['statuscode']==0:
                            s_resps.append({"server": server_response["sender"], "response":server_response["statusmsg"]})
                        else:
                            s_resps.append({"server": server_response["sender"], "message":server_response["statusmsg"]})
                    rdict.update({"result":s_resps})
                else:
                    rdict.update({"result": "KO", "message": "Error communicating with server"})
                
                rdict.update({'dialog_name':dialog_name})
                # And send it off.
            else:
                rdict.update({'bad':'true'})
                d = {}
                # This was painful, but I can't find a better way to extract the error messages:
                for e in form.errors.iteritems():
                    d.update({e[0]:unicode(e[1])}) # e[0] is the id, unicode(e[1]) is the error HTML.
                # Bung all that into the dict
                rdict.update({'errs': d })
                # Make a json whatsit to send back.
                
            return HttpResponse(json.dumps(rdict, ensure_ascii=False), mimetype='application/javascript')
        # It's a normal submit - non ajax.
        else:
            if form.is_valid():
                # We don't accept non-ajax requests for the moment
                return HttpResponseRedirect("/")
    else:
        # It's not post so make a new form
        logger.warn("Cannot access this page using GET")
        raise Http404
    

kermit-webui/kermit_new-webui/webui/platforms/views.py
'''
Created on Nov 3, 2011

@author: mmornati
'''
import logging
from django.shortcuts import render_to_response
from webui import settings, core
from django.template.context import RequestContext
from webui.abstracts import CoreService

logger = logging.getLogger(__name__)

def appdetails(request, appname):
    logger.debug("Application Details for %s" % appname)
    services = core.kermit_modules.extract(CoreService)
    service_status = []
    if services:
        for service in services:
            data = {"name": service.get_name(),
                    "description" : service.get_description(),
                    "status": service.get_status()}
            service_status.append(data)
    return render_to_response('platforms/application.html', {"base_url": settings.BASE_URL, "static_url":settings.STATIC_URL, "appname": appname ,"service_status":service_status}, context_instance=RequestContext(request))

kermit-webui/kermit_new-webui/templates/platforms/oc4j/application.html
{% load i18n %} <img class="introicon" src="{{static_url}}images/icons/application.png"/>
<div class="infohighlight">
	<strong>{{instance_id}}</strong>
	<br/>
	<strong>{% trans 'Server' %}</strong>: {{hostname}}
	<br/>
	<strong>{% trans 'Application Name' %}</strong>: {{application.name}}
	<br/>
	<strong>{% trans 'Application Version' %}</strong>: {{application.appliver.version}}
	<br/>
	<strong>{% trans 'Application Date' %}</strong>: {{application.appliver.versionDate}}
	<br/>
	<strong>{% trans 'Context' %}</strong>: {{application.root}}
	<br/>
	<strong>{% trans 'Load On Startup' %}</strong>: {{application.load_on_startup}}
	<br/>
</div>
<br/>
<div class="info">
	<table class="server-details">
		<thead>
			<tr>
				<th>{% trans 'Name' %}</th>
				<th>{% trans 'Server' %}</th>
				<th>{% trans 'Instance' %}</th>
				<th>{% trans 'User' %}</th>
				<th>{% trans 'Max-Connections' %}</th>
				<th>{% trans 'Min-Connections' %}</th>
				<th>{% trans 'Cached Statements' %}</th>
			</tr>
		</thead>
		<tbody>
			{% for pool in application.poollist%}
			<tr>
				<td>{{pool.name}}</td>
				<td>{{pool.datasource.bddserver}}</td>
				<td>{{pool.datasource.bddinstance}}</td>
				<td>{{pool.datasource.user}}</td>
				<td>{{pool.datasource.max_connections}}</td>
				<td>{{pool.datasource.min_connections}}</td>
				<td>{{pool.datasource.num_cached_statements}}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>

kermit-webui/kermit_new-webui/templates/platforms/oc4j/datasource.html
{% load i18n %} 
<img class="introicon" src="{{static_url}}images/icons/datasource.png"/>
<div class="info">
	<strong>{% trans 'Datasources' %}</strong>
	<table class="server-details">
		<thead>
			<tr>
				<th>{% trans 'Name' %}</th>
				<th>{% trans 'Server' %}</th>
				<th>{% trans 'Instance' %}</th>
				<th>{% trans 'User' %}</th>
				<th>{% trans 'Max-Connections' %}</th>
				<th>{% trans 'Min-Connections' %}</th>
				<th>{% trans 'Cached Statements' %}</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>{{datasource.name}}</td>
				<td>{{datasource.bddserver}}</td>
				<td>{{datasource.bddinstance}}</td>
				<td>{{datasource.user}}</td>
				<td>{{datasource.max_connections}}</td>
				<td>{{datasource.min_connections}}</td>
				<td>{{datasource.num_cached_statements}}</td>
			</tr>
		</tbody>
	</table>
</div>

kermit-webui/kermit_new-webui/templates/platforms/oc4j/datasources.html
{% load i18n %} 
<img class="introicon" src="{{static_url}}images/icons/datasources.png"/>
<div class="info">
	<strong>{% trans 'Datasources' %}</strong>
	<table class="server-details">
		<thead>
			<tr>
				<th>{% trans 'Name' %}</th>
				<th>{% trans 'Server' %}</th>
				<th>{% trans 'Instance' %}</th>
				<th>{% trans 'User' %}</th>
				<th>{% trans 'Max-Connections' %}</th>
				<th>{% trans 'Min-Connections' %}</th>
				<th>{% trans 'Cached Statements' %}</th>
			</tr>
		</thead>
		<tbody>
			{% for datasource in datasources%}
			<tr>
				<td>{{datasource.name}}</td>
				<td>{{datasource.bddserver}}</td>
				<td>{{datasource.bddinstance}}</td>
				<td>{{datasource.user}}</td>
				<td>{{datasource.max_connections}}</td>
				<td>{{datasource.min_connections}}</td>
				<td>{{datasource.num_cached_statements}}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>

kermit-webui/kermit_new-webui/templates/platforms/oc4j/deployform.html
<script>
	
	$('html').ajaxSend(function(event, xhr, settings) {
		if(!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
			// Only send the token to relative URLs i.e. locally.
			xhr.setRequestHeader("X-CSRFToken", $("#csrfmiddlewaretoken").val());
		}
	});

	$(document).ready(function() {
		$('.errorlist').remove();
		// prepare Options Object
		var options = {
			url : '{% url oc4j_deploy_app filters "deploy-dialog" "xhr" %}', // Here we pass the xhr flag
			dataType : 'json',
			success : parseResponse,
			error: parseError,
			beforeSubmit : beforeForm
		};
		// bind form using ajaxForm
		$('#tf').ajaxForm(options);
		
		$("#id_types").change(function() {
			$.ajax({
				// The link we are accessing.
				url : '{{base_url}}/platform/oc4j/applist/{{filters}}/' + this.value +'/',
				// The type of request.
				type : "get",
				// The type of data that is getting returned.
				dataType : "json",
				error : function() {
					//TODO: Show error message
					alert("Server communication error. Cannot download application List");
					$('#loading').hide();
				},
				beforeSend : function() {
					$('#loading').show();
				},
				complete : function() {
					$('#loading').hide();
				},
				success : function(data) {
					$("#id_applist").empty();
					if (data.errors) {
						alert(data.errors);
					} else {
						for(i in data.applist) {
							content = "<option value='" + data.applist[i] + "'>" + data.applist[i] + "</option>";
							$(content).appendTo("#id_applist");
						}
					}
				}
			});
		});
		
		$.ajax({
				// The link we are accessing.
				url : '{{base_url}}/platform/oc4j/instancelist/{{filters}}/',
				// The type of request.
				type : "get",
				// The type of data that is getting returned.
				dataType : "json",
				error : function() {
					//TODO: Show error message
					alert("Server communication error. Cannot get instances list for selected server");
					$('#loading').hide();
				},
				beforeSend : function() {
					$('#loading').show();
				},
				complete : function() {
					$('#loading').hide();
				},
				success : function(data) {
					$("#id_instancename").empty();
					if (data.errors) {
						alert(data.errors);
					} else {
						for(i in data.instances) {
							content = "<option value='" + data.instances[i] + "'>" + data.instances[i] + "</option>";
							$(content).appendTo("#id_instancename");
						}
					}
				}
			});
	});
	
	function parseResponse(data) {
		$('#loading').hide();
		if(data) {
			// Build a var. NOTE: Make sure your id name (this is a div) is NOT THE SAME
			// as any var in javascript -- ie has a fit and barfs errors.
			e_msg = "We received your form, thank you.";
			// Did we set the 'bad' flag in Django?
			// Use eval() to turn the stuff in the data object into actual vars.
			if(eval(data.bad)) {
				e_msg = "Please check your form.";
				errors = eval(data.errs);
				//Again with the eval :)
				// This is very nice: Go thru the errors, build an id name and
				// then access that tag and add the HTML from the Django error
				$.each(errors, function(fieldname, errmsg) {
					id = "#id_" + fieldname;
					$(id).parent().before(errmsg);
					//I want the error above the <p> holding the field
				});
				// re-enable the submit button, coz user has to fix stuff.
//				$('#bt').attr("disabled", "");
			} else {
				if (data.result!="KO") {
					for (server_resp in data.result) {
						if (data.result[server_resp].message!=undefined) {
							$("#emsg").append("<div class='errorbox'>" + data.result[server_resp].server + ": " + data.result[server_resp].message + "</div><br/>").fadeIn("slow");
						} else {
							$("#emsg").append("<div class='messagebox'>" + data.result[server_resp].server + ": " + data.result[server_resp].response + "</div><br/>").fadeIn("slow");			
						}
					}
				} else {
					$("#emsg").html("<div class='errorbox'>" + data.message + "</div><br/>").fadeIn("slow");	
				}
			}
		} else {
			//DON'T PANIC :D
			$('#emsg').text("Ajax error : no data received. ").fadeIn("slow");
		}
	}
	
	function parseError(data) {
		$('#loading').hide();
		if(data) {
			alert(data.result);				
			$("#" + data.dialog_name).dialog('close');
		} else {
			//DON'T PANIC :D
			$('#emsg').text("Ajax error : no data received. ").fadeIn("slow");
		}
	}

	function beforeForm() {
		//$('#bt').attr("disabled", "disabled");
		//Disable the submit button - can't click twice
		$('.errorlist').remove();
		//Get rid of any old error uls
		$('#emsg').empty();
		$('#emsg').fadeOut('slow');
		$('#loading').show();
		//Get rid of the main error message
		return true;
		//Might not need this...
	}
</script>
<p>
	Parameters required to execute {{action}}
</p>
<div id="emsg">
	&nbsp;
</div>
<form action="{% url oc4j_deploy_app filters 'deploy-dialog' None%}" method="post" id="tf">
	{% csrf_token %}
		<fieldset>
		{% for field in form %}
	        <div class="fieldWrapper">
	        	
	            {{ field.errors }}
	            {% if field.field.required %}
	            <p><b>{{ field.label_tag }}</b>: {{ field }}</p>
	            {% else %}
	            <p>{{ field.label_tag }}: {{ field }}</p>
	            {% endif %}
	            
	        </div>
	    {% endfor %}
		<br/>
		<input type="hidden" name="action" id="id_action" value="{{action}}"/>
		<input class="input" type="submit" value="Execute" id="bt"/>
	</fieldset>
</form>

kermit-webui/kermit_new-webui/templates/platforms/oc4j/instance.html
{% load i18n %} 
<img class="introicon" src="{{static_url}}images/icons/app-settings.png"/>
<div class="info">
	<strong>{% trans 'Java Version'%}</strong>
	<div class="codestyle">
		{{java_version}}
	</div>
	<br/>
	<strong>{% trans 'OC4J Options'%}</strong>
	<div class="codestyle">
		{% for opt in oc4j_options%}
			 {{opt}} <br/>
		{% endfor %}
	</div>
	<br/>
	<strong>{% trans 'Java Start Options'%}</strong>
	<div class="codestyle">
		{% for opt in java_start_options%}
			{{opt}} <br/>
		{% endfor %}
	</div>
	<br/>
	<strong>{% trans 'Java Stop Options'%}</strong>
	<div class="codestyle">
		{% for opt in java_stop_options%}
			 {{opt}} <br/>
		{% endfor %}
	</div>
</div>